credentials:
  usernames:
    maths:
      email: maths@example.com
      name: Mathematics Dept
      password: "mathspass"
    chemistry:
      email: chemistry@example.com
      name: Chemistry Dept
      password: "chem123"
    physics:
      email: physics@example.com
      name: Physics Dept
      password: "phy123"
    biology:
      email: biology@example.com
      name: Biology Dept
      password: "bio123"
    computerscience:
      email: cs@example.com
      name: Computer Science Dept
      password: "cs123"
    english:
      email: english@example.com
      name: English Dept
      password: "eng123"
    hindi:
      email: hindi@example.com
      name: Hindi Dept
      password: "hin123"
    commerce:
      email: commerce@example.com
      name: Commerce Dept
      password: "com123"
    socialscience:
      email: social@example.com
      name: Social Science Dept
      password: "soc123"

cookie:
  name: MBReportCookie
  key: some_random_key_123
  expiry_days: 7
